### PR TITLE
v1.0

### PR DESCRIPTION
**Pull request by andyb3**
This change is [Reviewable](https://reviewable.io/reviews/moka-guys/100k_check_labkey/1)

### CODE REVIEW

**Review by aledj2 — COMMENTED** [review]
+@aledj2 

> *[Reviewable](https://reviewable.io/reviews/moka-guys/100k_check_labkey/1#-:-LZngwi55ZvFRN8wkHZx:bweg3f8)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @aledj2)

**Review by aledj2 — CHANGES_REQUESTED** [review]
Bit confused about the use (or not) of netrc file and the optional user /password args.

> Reviewed 1 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/100k_check_labkey/1#-:-LZnkLz97kwIysFsZbKX:b-r5685q)* status: 1 of 4 files reviewed, 11 unresolved discussions (waiting on @aledj2 and @andyb3)

___
*[LabKey.py, line 64 at r1](https://reviewable.io/reviews/moka-guys/100k_check_labkey/1#-LZnkvqd9uZeh_HSqUpV:-LZnkvqd9uZeh_HSqUpW:b-p347aa) ([raw file](https://github.com/moka-guys/100k_check_labkey/blob/f333ed0b5fe47e56fb32c917411d72190bbf2c06/LabKey.py#L64)):*
> ```
> participant_id,person_identifier,date_of_birth,forenames,surname,person_identifier_type
> ```
Can these columns be described in comments or docstring?
___
*[LabKey.py, line 67 at r1](https://reviewable.io/reviews/moka-guys/100k_check_labkey/1#-LZnk3D8B6HBM2Kx9lgN:-LZnk3D8B6HBM2Kx9lgO:b-pi40i2) ([raw file](https://github.com/moka-guys/100k_check_labkey/blob/f333ed0b5fe47e56fb32c917411d72190bbf2c06/LabKey.py#L67)):*
> ```Python
>             'query.participant_id~eq': self.PID}
>         # Make API call with auth credentials if provided.
>         if self.uname or self.pwd:
> ```

as below should this be and not or?
___
*[LabKey.py, line 74 at r1](https://reviewable.io/reviews/moka-guys/100k_check_labkey/1#-LZnke_N2BrVXKiZ8zG6:-LZnke_N2BrVXKiZ8zG7:be5ak7q) ([raw file](https://github.com/moka-guys/100k_check_labkey/blob/f333ed0b5fe47e56fb32c917411d72190bbf2c06/LabKey.py#L74)):*
> ```Python
>         # Raise error if more or less than one participant is matched by the PID. This is because PIDs are unique.
>         if response_json['rowCount'] != 1:
>             raise IndexError('More/less than one row returned for participant ID {}'.format(self.PID))
> ```

can you say how many rows are returned in the error message?
___
*[LabKey.py, line 77 at r1](https://reviewable.io/reviews/moka-guys/100k_check_labkey/1#-LZnlRiw8S1nraj2VSUM:-LZnlRiw8S1nraj2VSUN:b-vqkrtn) ([raw file](https://github.com/moka-guys/100k_check_labkey/blob/f333ed0b5fe47e56fb32c917411d72190bbf2c06/LabKey.py#L77)):*
> ```Python
>         return(response_json)
>     
>     def print_data(self):
> ```

is this actually used? Does it warrant a function?
___
*[LabKey.py, line 81 at r1](https://reviewable.io/reviews/moka-guys/100k_check_labkey/1#-LZnlpwE1pOL12RY_Hlk:-LZnlpwE1pOL12RY_Hll:bcpb5fx) ([raw file](https://github.com/moka-guys/100k_check_labkey/blob/f333ed0b5fe47e56fb32c917411d72190bbf2c06/LabKey.py#L81)):*
> ```Python
> 
>     def print_details(self):
>         print(",".join([self.name, self.dob, self.nhsid]), end="")
> ```

Does this warrant a function - isn't reused and is quite specific.
___
*[LabKey.py, line 92 at r1](https://reviewable.io/reviews/moka-guys/100k_check_labkey/1#-LZnjCYCC4sJbQW6niiN:-LZnjCYCC4sJbQW6niiO:bwcgeh0) ([raw file](https://github.com/moka-guys/100k_check_labkey/blob/f333ed0b5fe47e56fb32c917411d72190bbf2c06/LabKey.py#L92)):*
> ```Python
> 
>     # Call LabKey_HTTP() with Participant ID
>     if parsed_args.username or parsed_args.password:
> ```

What is only one arg is given? Maybe if set them to None if not given and then pass all three to labkey_http()?
___
*[LabKey.py, line 92 at r1](https://reviewable.io/reviews/moka-guys/100k_check_labkey/1#-LZnjqDF8KU6XUKAWQ_a:-LZnjqDF8KU6XUKAWQ_b:b-7avrqp) ([raw file](https://github.com/moka-guys/100k_check_labkey/blob/f333ed0b5fe47e56fb32c917411d72190bbf2c06/LabKey.py#L92)):*
> ```Python
> 
>     # Call LabKey_HTTP() with Participant ID
>     if parsed_args.username or parsed_args.password:
> ```

The .netrc file isn't used at all?
___
*[test_labkey.py, line 7 at r1](https://reviewable.io/reviews/moka-guys/100k_check_labkey/1#-LZnm38o52aSKluNFbDf:-LZnm38o52aSKluNFbDg:bhsko63) ([raw file](https://github.com/moka-guys/100k_check_labkey/blob/f333ed0b5fe47e56fb32c917411d72190bbf2c06/test_labkey.py#L7)):*
> ```Python
> # Read test patient data
> with open('test_data.txt') as f:
>     PID, DOB, NHSID = [ line.rstrip('\n') for line in f.readlines() ]
> ```

assuming there is only one line in this file, or you're only using the last line in file? If so just use readline()
___
*[test_labkey.py, line 11 at r1](https://reviewable.io/reviews/moka-guys/100k_check_labkey/1#-LZnmLUVDCEs12JMY7Gd:-LZnmLUVDCEs12JMY7Ge:bekgb7b) ([raw file](https://github.com/moka-guys/100k_check_labkey/blob/f333ed0b5fe47e56fb32c917411d72190bbf2c06/test_labkey.py#L11)):*
> ```Python
> with open('/home/mokaguys/.netrc') as f:
>     csv = [ line.split(' ') for line in f.readlines() ]
>     MACHINE, UNAME, PWD = [ columns[1].rstrip('\n') for columns in csv ]
> ```

what is this doing? maybe could provide example .netrc file, or the format at least?
___
*[test_labkey.py, line 13 at r1](https://reviewable.io/reviews/moka-guys/100k_check_labkey/1#-LZnms9d6MlG6cYJwn8B:-LZnms9d6MlG6cYJwn8C:b-p1lgid) ([raw file](https://github.com/moka-guys/100k_check_labkey/blob/f333ed0b5fe47e56fb32c917411d72190bbf2c06/test_labkey.py#L13)):*
> ```Python
>     MACHINE, UNAME, PWD = [ columns[1].rstrip('\n') for columns in csv ]
> 
> def test_optional_inputs():
> ```

is this called anywhere? or is this set off manully?
___
*[test_labkey.py, line 24 at r1](https://reviewable.io/reviews/moka-guys/100k_check_labkey/1#-LZnnA_XBrEwQ145M_DN:-LZnnA_XBrEwQ145M_DO:b-3wmlx8) ([raw file](https://github.com/moka-guys/100k_check_labkey/blob/f333ed0b5fe47e56fb32c917411d72190bbf2c06/test_labkey.py#L24)):*
> ```Python
>     LabKey.main()
> 
> @pytest.fixture
> ```

how are these used?

**Review by andyb3 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/100k_check_labkey/1)* status: 1 of 4 files reviewed, 11 unresolved discussions (waiting on @aledj2 and @andyb3)

___
*[LabKey.py, line 64 at r1](https://reviewable.io/reviews/moka-guys/100k_check_labkey/1#-LZnkvqd9uZeh_HSqUpV:-LZnzABHBBrOERIHTkyL:b-896fix) ([raw file](https://github.com/moka-guys/100k_check_labkey/blob/f333ed0b5fe47e56fb32c917411d72190bbf2c06/LabKey.py#L64)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

> ```
> participant_id,person_identifier,date_of_birth,forenames,surname,person_identifier_type
> ```
Can these columns be described in comments or docstring?
</blockquote></details>

Done.
___
*[LabKey.py, line 67 at r1](https://reviewable.io/reviews/moka-guys/100k_check_labkey/1#-LZnk3D8B6HBM2Kx9lgN:-LZnzNsGAaEccMgw_31C:b-896fix) ([raw file](https://github.com/moka-guys/100k_check_labkey/blob/f333ed0b5fe47e56fb32c917411d72190bbf2c06/LabKey.py#L67)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

as below should this be and not or?
</blockquote></details>

Done.
___
*[LabKey.py, line 74 at r1](https://reviewable.io/reviews/moka-guys/100k_check_labkey/1#-LZnke_N2BrVXKiZ8zG6:-LZo1n23CNLyLJdhW5BM:b-896fix) ([raw file](https://github.com/moka-guys/100k_check_labkey/blob/f333ed0b5fe47e56fb32c917411d72190bbf2c06/LabKey.py#L74)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

can you say how many rows are returned in the error message?
</blockquote></details>

Done.
___
*[LabKey.py, line 77 at r1](https://reviewable.io/reviews/moka-guys/100k_check_labkey/1#-LZnlRiw8S1nraj2VSUM:-LZo24_u7f2uzdsC0WOH:btcdy0p) ([raw file](https://github.com/moka-guys/100k_check_labkey/blob/f333ed0b5fe47e56fb32c917411d72190bbf2c06/LabKey.py#L77)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

is this actually used? Does it warrant a function?
</blockquote></details>

Doesn't appear to be used, have removed
___
*[LabKey.py, line 81 at r1](https://reviewable.io/reviews/moka-guys/100k_check_labkey/1#-LZnlpwE1pOL12RY_Hlk:-LZo3NQpB39i00a0EjEw:b-896fix) ([raw file](https://github.com/moka-guys/100k_check_labkey/blob/f333ed0b5fe47e56fb32c917411d72190bbf2c06/LabKey.py#L81)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

Does this warrant a function - isn't reused and is quite specific.
</blockquote></details>

Done.
___
*[LabKey.py, line 92 at r1](https://reviewable.io/reviews/moka-guys/100k_check_labkey/1#-LZnjCYCC4sJbQW6niiN:-LZo3PY01kbImenM-U_8:b-3hvfnt) ([raw file](https://github.com/moka-guys/100k_check_labkey/blob/f333ed0b5fe47e56fb32c917411d72190bbf2c06/LabKey.py#L92)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

What is only one arg is given? Maybe if set them to None if not given and then pass all three to labkey_http()?
</blockquote></details>

If no argument is supplied by user argparse sets value to None anyway, so no need for this if statement
___
*[LabKey.py, line 92 at r1](https://reviewable.io/reviews/moka-guys/100k_check_labkey/1#-LZnjqDF8KU6XUKAWQ_a:-LZo3etz-oPsut7flqaz:b-5skwuu) ([raw file](https://github.com/moka-guys/100k_check_labkey/blob/f333ed0b5fe47e56fb32c917411d72190bbf2c06/LabKey.py#L92)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

The .netrc file isn't used at all?
</blockquote></details>

yeah by default uses credentials in netrc, but can override this by specifying username and password on command line. Have added details for this into the help message

**Review by andyb3 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/moka-guys/100k_check_labkey/1)* status: 1 of 6 files reviewed, 11 unresolved discussions (waiting on @aledj2)

___
*[test_labkey.py, line 7 at r1](https://reviewable.io/reviews/moka-guys/100k_check_labkey/1#-LZnm38o52aSKluNFbDf:-LZoOYGs8WTUM7s5Yzva:b-n50rls) ([raw file](https://github.com/moka-guys/100k_check_labkey/blob/f333ed0b5fe47e56fb32c917411d72190bbf2c06/test_labkey.py#L7)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

assuming there is only one line in this file, or you're only using the last line in file? If so just use readline()
</blockquote></details>

There's 3 lines, have added comment to make this clear
___
*[test_labkey.py, line 11 at r1](https://reviewable.io/reviews/moka-guys/100k_check_labkey/1#-LZnmLUVDCEs12JMY7Gd:-LZoVLqO7vQGaHI9tdJg:bdrrzd9) ([raw file](https://github.com/moka-guys/100k_check_labkey/blob/f333ed0b5fe47e56fb32c917411d72190bbf2c06/test_labkey.py#L11)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

what is this doing? maybe could provide example .netrc file, or the format at least?
</blockquote></details>

Have added an example netrc file and documentation is linked in readme
___
*[test_labkey.py, line 13 at r1](https://reviewable.io/reviews/moka-guys/100k_check_labkey/1#-LZnms9d6MlG6cYJwn8B:-LZoVUh5-8lCXxUO7GF3:bs7wiuf) ([raw file](https://github.com/moka-guys/100k_check_labkey/blob/f333ed0b5fe47e56fb32c917411d72190bbf2c06/test_labkey.py#L13)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

is this called anywhere? or is this set off manully?
</blockquote></details>

pytest runs these functions, starting with `test_` indicates they are a test. Have added instructions to README on how to run.
___
*[test_labkey.py, line 24 at r1](https://reviewable.io/reviews/moka-guys/100k_check_labkey/1#-LZnnA_XBrEwQ145M_DN:-LZoVkop-tscQSWkXU6o:b-w5qmgq) ([raw file](https://github.com/moka-guys/100k_check_labkey/blob/f333ed0b5fe47e56fb32c917411d72190bbf2c06/test_labkey.py#L24)):*
<details><summary><i>Previously, aledj2 (Aled Jones) wrote…</i></summary><blockquote>

how are these used?
</blockquote></details>

I believe pytest.fixture is a way of creating an object that can be used downstream by pytest tests

**Review by aledj2 — APPROVED** [review]
:lgtm: 

> Reviewed 5 of 5 files at r2.
> *[Reviewable](https://reviewable.io/reviews/moka-guys/100k_check_labkey/1#-:-LZoe-_dCfvKoT8c_a3b:bg7igkv)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
